project:
  type: website

website:
  title: "An Thien Tran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments and Labs
        menu:
          - assignment02.qmd
      - href: about.qmd
        text: About
      - href: CV.pdf
        text: CV

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual